### ISSUE TITLE
Clear documentation for the functions?

### ISSUE THREAD

**Issue by JuicyFandango** [sdesyllas/RiotApi.NET#3]

**Comment by sdesyllas** [comment]
The documentation is written on all functions in each interface. I changed project build options to emit comments in xml file along with the dll. Thinking of using doxygen or some other document html generator to include html documentation as well.

**Comment by sdesyllas** [comment]
The things that I did to resolve this one are 
* Added detailed XML summaries to all methods and functions for each part of the service
* Generated a full api reference documentation in chm standard format which can be found here https://github.com/sdesyllas/RiotApi.NET/tree/master/Documentation/Help
* Added Sandcastle documentation project so that the full api reference will be updated for each change in the code
